language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-24
# Support library
    - extra-android-support
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
  licenses:
    - '.+'

before_script:
    - cd Android
    - chmod +x gradlew

script:
   - chmod +x ./gradlew
   - ./gradlew assembleDebug assembleRelease
